#生产环境的配置
#用户会话过期时间，单位秒
#Tomcat编码,默认就是UTF-8
#server.port=8443
server:
  port: 8080
  session:
    timeout: 60
  tomcat:
    uri-encoding: UTF-8
# SSL协议相关配置
#server.ssl.key-store= .keystore
#server.ssl.key-password= 123321
#server.ssl.key-store-type= JKS
#server.ssl.key-alias= tomcat

spring:
    application:
        name: prod
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://rdsjsc997jy379s53w68o.mysql.rds.aliyuncs.com:3306/znblog?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: qiuxm
        password: 123321qq
        type: com.alibaba.druid.pool.DruidDataSourceC3P0Adapter
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

#jms相关配置
activemq:
    broker-url: spring.activemq.broker-url=tcp://120.26.231.72:61616

#mybatis配置
mybatis:
    mapperLocations: classpath:mapping/*.xml

#业务参数属性配置
#book:
#  author: 菡萏如佳人
#  name: 程序与诗
#
#author:
#  name: 临江仙
#  age:  32